### ISSUE TITLE
RTL patch does not work on newer Claude Desktop versions

### ISSUE THREAD

**Issue by yochaiherbst-gif** [shraga100/claude-desktop-rtl-patch#36]
Hi, and thank you for this patch!

I'm running into a problem with the newer versions of Claude Desktop. When I install the patch, it appears to install successfully, but when I open Claude Desktop I do not see the confirmation message that the RTL support was installed successfully.

In addition, the text is still displayed incorrectly (sentences appear jumbled / not right-to-left), so it does not look like the patch is actually applied.

Could you please update the patch to support the latest versions of Claude Desktop? Thank you!

**Comment by shraga100** [comment]
היי,
אצלי זה עובד תקין גם בגירסאות החדשות.
תוכל לצרף את הלוג/ים/ מכאן?
C:\ProgramData\ClaudeRtlPatch

**Comment by avish999** [comment]
Adding a data point from 1.22209.0.0 — my symptom is more specific than the OP's: the patch applies fine, but it breaks Claude Code / Cowork session start. Chat works, but starting a local session immediately fails with:

> Something went wrong — u._addDefaultMeta is not a function

Worked on 1.20186.x; broke after updating to 1.22209.0.0 (MSIX, Windows, PowerShell 5.1). Stack trace from main.log (ids redacted) — the crash is on the session-start path, inside injected renderer chunks:

```
[error] Sentry caught: TypeError: u._addDefaultMeta is not a function
    at s.<computed> (app://\.vite\build\index.chunk-Cr-17X6C.js:989:1134)
    at G._fetchBaseQueryConfig (app://\.vite\build\index.chunk-Bwyu1Jht.js:1324:16543)
    at async Promise.all (index 1)
    at async G.startSession (app://\.vite\build\index.chunk-Bwyu1Jht.js:1313:14176)
    at async Object.start (app://\.vite\build\index.chunk-DhJl-RT6.js:975:4972)
[error] Cannot start session local_<redacted>: u._addDefaultMeta is not a function
```

patch.log from that run: "Injected RTL JS logic into 102 file(s)", including many index.chunk-*.js. The two chunks in the crash are renderer chunks the patch injects into — and chunk names / minified vars regenerate per build, so injection that was safe on 1.20186.x lands differently here. _addDefaultMeta is a Winston internal, so u (the logger) is getting detached/shadowed on that path.

Restoring the pristine app.asar / claude.exe / cowork-svc.exe from .bak plus removing the self-signed certs fully fixes it; re-applying reproduces it. Possible fix: exclude the session/base-query renderer chunk from injection (like the MCP host/worker files already skipped), or wrap the payload in its own IIFE so it can't shadow module-scoped bindings. Happy to test a build against 1.22209.0.0 and share the full logs.

**Comment by shraga100** [comment]
Thanks @avish999 — outstanding report; the line numbers and the restore-reproduce cycle made this diagnosable. Confirmed: **real patch bug**, now fixed in 2b99e6a (pushed to `main`).

**Root cause — strict-mode demotion, not shadowing.** The payload was already IIFE-wrapped with a `typeof document` guard, so it couldn't shadow module bindings. But it was *bare-prepended* ahead of each file's `"use strict";` — and a strict directive only counts as a directive when it's the **first statement**. On 1.22209.0.0 every one of the 102 injected files starts with `"use strict";`, so all of them silently dropped to sloppy mode.

Your crash site (the payload adds 956 lines, so stack line 989 → pristine line 33) is winston's level-method shim:

```js
s.prototype[c] = function(...l){ const u = this || a; ... u._addDefaultMeta(f), u.write(f) ... }
```

Strict mode: detached call → `this === undefined` → `u = a` (the default logger) → works.
Sloppy mode: `this === globalThis` (truthy!) → `u = globalThis` → **`u._addDefaultMeta is not a function`**. Exactly your error — and it explains why chat worked while only session start broke: the crash needs a detached logger call on the `_fetchBaseQueryConfig` path, which is environment-dependent (that's also why it didn't reproduce on my machine).

**Fix:** the payload is now inserted *after* the `"use strict";` prologue, mirroring what the main-entry injection already did. Verified by re-running the full injection over an extracted 1.22209.0.0 `app.asar`: 103/103 strict-first preserved, `node --check` clean on your crash chunks, and a probe module built from the real payload + that exact winston pattern reproduces your error with the old injection and passes with the new one.

(Re your suggestions: the IIFE was already there, and excluding the chunks isn't needed — the payload is inert outside the renderer; only the directive demotion was harmful.)

**Please try again**: pull the latest `patch.ps1` (or re-download from `main`) and re-run — it restores from the `.bak` files first, so it applies cleanly on top of your current state. Would love confirmation from your machine, including that Claude Code / Cowork session start now works.

**Comment by avish999** [comment]
Confirmed fixed on my machine. Pulled the updated patch, re-applied on 1.22209.0.0, and Claude Code / Cowork session start now works cleanly — no more u._addDefaultMeta — with RTL back in place. Thanks for the fast turnaround and the clear root-cause writeup; the strict-mode directive-placement explanation makes complete sense.
